"""add_coin_tables

Revision ID: 7992d9813738
Revises: c4d7e8f9a1b2
Create Date: 2026-03-14 12:48:03.793721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7992d9813738'
down_revision: Union[str, None] = 'c4d7e8f9a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_activity_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=True),
    sa.Column('trading_date', sa.Date(), nullable=True),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('coin_asset_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(length=30), nullable=True),
    sa.Column('llm_tier', sa.String(length=10), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_activity_logs_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_activity_logs_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_activity_logs_trading_date'), ['trading_date'], unique=False)

    op.create_table('coin_analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coin_asset_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('recommendation', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(length=20), nullable=False),
    sa.Column('llm_tier', sa.String(length=10), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_analysis_results_coin_asset_id'), ['coin_asset_id'], unique=False)

    op.create_table('coin_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_assets_symbol'), ['symbol'], unique=True)

    op.create_table('coin_broker_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('coin_name', sa.String(length=200), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('strategy_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('requested_price', sa.Float(), nullable=False),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('bithumb_order_id', sa.String(length=100), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_broker_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_broker_orders_bithumb_order_id'), ['bithumb_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_broker_orders_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_broker_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_broker_orders_symbol'), ['symbol'], unique=False)

    op.create_table('coin_daily_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_cycles', sa.Integer(), nullable=False),
    sa.Column('total_analyses', sa.Integer(), nullable=False),
    sa.Column('total_recommendations', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('buy_count', sa.Integer(), nullable=False),
    sa.Column('sell_count', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('open_position_count', sa.Integer(), nullable=False),
    sa.Column('total_24h_volume', sa.Float(), nullable=False),
    sa.Column('btc_dominance', sa.Float(), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=False),
    sa.Column('market_summary', sa.Text(), nullable=True),
    sa.Column('performance_review', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('next_day_plan', sa.Text(), nullable=True),
    sa.Column('top_picks', sa.Text(), nullable=True),
    sa.Column('strategy_stats', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date', name='uq_coin_daily_reports_report_date')
    )
    with op.batch_alter_table('coin_daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_daily_reports_report_date'), ['report_date'], unique=False)

    op.create_table('coin_holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coin_asset_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_buy_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_holdings_coin_asset_id'), ['coin_asset_id'], unique=False)

    op.create_table('coin_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coin_asset_id', sa.String(length=36), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=False),
    sa.Column('bithumb_order_id', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_orders_bithumb_order_id'), ['bithumb_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_orders_coin_asset_id'), ['coin_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_orders_status'), ['status'], unique=False)

    op.create_table('coin_trade_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('coin_name', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('strategy_type', sa.String(length=30), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('is_win', sa.Boolean(), nullable=False),
    sa.Column('hold_hours', sa.Integer(), nullable=False),
    sa.Column('exit_reason', sa.String(length=30), nullable=False),
    sa.Column('ai_recommendation', sa.String(length=10), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('ai_target_price', sa.Float(), nullable=True),
    sa.Column('ai_stop_loss_price', sa.Float(), nullable=True),
    sa.Column('entry_rsi', sa.Float(), nullable=True),
    sa.Column('entry_macd_hist', sa.Float(), nullable=True),
    sa.Column('entry_bb_position', sa.String(length=20), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=False),
    sa.Column('btc_dominance', sa.Float(), nullable=True),
    sa.Column('entry_24h_volume', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entry_at', sa.DateTime(), nullable=True),
    sa.Column('exit_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_trade_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_trade_results_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_trade_results_strategy_type'), ['strategy_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_trade_results_symbol'), ['symbol'], unique=False)

    op.create_table('coin_trading_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('strategy_type', sa.String(length=30), nullable=False),
    sa.Column('param_name', sa.String(length=50), nullable=False),
    sa.Column('param_value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_report_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_trading_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_trading_rules_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_trading_rules_rule_type'), ['rule_type'], unique=False)

    op.create_table('coin_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coin_asset_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('suggested_price', sa.Float(), nullable=False),
    sa.Column('suggested_quantity', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['coin_analysis_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_recommendations_coin_asset_id'), ['coin_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_recommendations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_recommendations_status'))
        batch_op.drop_index(batch_op.f('ix_coin_recommendations_coin_asset_id'))

    op.drop_table('coin_recommendations')
    with op.batch_alter_table('coin_trading_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_trading_rules_rule_type'))
        batch_op.drop_index(batch_op.f('ix_coin_trading_rules_is_active'))

    op.drop_table('coin_trading_rules')
    with op.batch_alter_table('coin_trade_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_trade_results_symbol'))
        batch_op.drop_index(batch_op.f('ix_coin_trade_results_strategy_type'))
        batch_op.drop_index(batch_op.f('ix_coin_trade_results_order_id'))

    op.drop_table('coin_trade_results')
    with op.batch_alter_table('coin_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_orders_status'))
        batch_op.drop_index(batch_op.f('ix_coin_orders_coin_asset_id'))
        batch_op.drop_index(batch_op.f('ix_coin_orders_bithumb_order_id'))

    op.drop_table('coin_orders')
    with op.batch_alter_table('coin_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_holdings_coin_asset_id'))

    op.drop_table('coin_holdings')
    with op.batch_alter_table('coin_daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_daily_reports_report_date'))

    op.drop_table('coin_daily_reports')
    with op.batch_alter_table('coin_broker_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_broker_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_coin_broker_orders_status'))
        batch_op.drop_index(batch_op.f('ix_coin_broker_orders_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_coin_broker_orders_bithumb_order_id'))

    op.drop_table('coin_broker_orders')
    with op.batch_alter_table('coin_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_assets_symbol'))

    op.drop_table('coin_assets')
    with op.batch_alter_table('coin_analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_analysis_results_coin_asset_id'))

    op.drop_table('coin_analysis_results')
    with op.batch_alter_table('coin_activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_activity_logs_trading_date'))
        batch_op.drop_index(batch_op.f('ix_coin_activity_logs_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_coin_activity_logs_activity_type'))

    op.drop_table('coin_activity_logs')
    # ### end Alembic commands ###
